name: "push to main"
on:
  push:
    branches:
    - main

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ secrets.ORG_ADMIN_ID }}:role/GithubActionRole
        role-session-name: GithubActionSession

    - uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Apply
      id: apply
      env:
        TF_VAR_org_admin_id: ${{ secrets.ORG_ADMIN_ID }}
        TF_VAR_org_account1_id: ${{ secrets.ORG_ACCOUNT1_ID }}
        TF_VAR_slack_aws_alert_url: ${{ secrets.SLACK_AWS_ALERT_URL }}
      run: terraform apply -auto-approve
